---
version: 3

dependencies:
  ansible_core:
    package_pip: ansible-core==2.15.3
  ansible_runner:
    package_pip: ansible-runner
  galaxy: requirements.yml
  python: requirements.txt
  # system: bindep.txt

images:
  base_image:
    name: docker.io/library/ubuntu:22.04

additional_build_files:
  - src: ansible.cfg
    dest: configs

additional_build_steps:
  prepend_base: |
    RUN apt-get -y update \
      && apt-get -y upgrade \
      && apt-get -y install python3 python3-venv \
      && rm -rf /var/lib/apt/lists/*
