name: build

on:
  push:
    branches: [main]

# env:
#   REGISTRY: ghcr.io
#   IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.6.1"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.16"
          cache: poetry

      # - name: Install ansible-builder
      #   run: pip3 install ansible-builder==3.0.0

      # - name: Log into registry ${{ env.REGISTRY }}
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Get current date
      #   id: date
      #   run: echo "DATE=$(date +%Y%m%d)" >>$GITHUB_ENV

      # - name: Build and Push AWX EE image
      #   run: |
      #     ansible-builder build \
      #     --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest \
      #     --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.DATE }} \
      #     --container-runtime docker \
      #     -v 3

      # - name: Push AWX EE image
      #   run: |
      #     docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest && \
      #     docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.DATE }}
