name: Build EE

on:
  push:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/test-ee

jobs:
  build:
    name: Build EE
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.16"

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.6.1"

      - name: Poetry
        run: |
          poetry install

      - name: Get yyymmdd
        run: echo "DATE=$(date +%Y%m%d)" >>$GITHUB_ENV

      - name: Build EE
        run: |
          echo "::group::Build EE"
          poetry run \
            ansible-builder build \
              --container-runtime docker \
              --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest \
              --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.DATE }} \
              --verbosity 3
          echo "::endgroup::"

      - name: Login to ${{ env.REGISTRY }} Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push EE
        run: |
          echo "::group::Push EE"
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.DATE }}
          echo "::endgroup::"
