name: Build EE

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build EE
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      matrix:
        registry: ["ghcr.io"]
        image-name: ["${{ github.repository }}/test-ee"]
        poetry-version: ["1.6.1"]
        python-version: ["3.9.16"]
        working-directory: ["ees/test-ee"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Poetry install
        run: |
          poetry install

      - name: Get yyymmdd
        run: echo "DATE=$(date +%Y%m%d)" >>$GITHUB_ENV

      - name: Build EE
        working-directory: ${{ matrix.working-directory }}
        run: |
          echo "::group::Build EE"
          poetry run \
            ansible-builder build \
              --container-runtime docker \
              --tag ${{ matrix.registry }}/${{ matrix.image-name }}:latest \
              --tag ${{ matrix.registry }}/${{ matrix.image-name }}:${{ env.DATE }} \
              --verbosity 3
          echo "::endgroup::"

      - name: Login to ${{ matrix.registry }} Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ matrix.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push EE
        working-directory: ${{ matrix.working-directory }}
        run: |
          echo "::group::Push EE"
          docker push ${{ matrix.registry }}/${{ matrix.image-name }}:latest
          docker push ${{ matrix.registry }}/${{ matrix.image-name }}:${{ env.DATE }}
          echo "::endgroup::"
