name: Build, push, test EE

on:
  push:
    branches: [main]

jobs:
  build-push-test:
    name: Build, push, test EE
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        image:
          - image-registry: "ghcr.io"
            image-name: "${{ github.repository }}/test-ee-1"
            poetry-version: "1.6.1"
            python-version: "3.9.16"
            working-directory: "ees/test-ee-1"
            build-with: ansible-builder
          - image-registry: "ghcr.io"
            image-name: "${{ github.repository }}/test-ee-2"
            poetry-version: "1.6.1"
            python-version: "3.9.16"
            working-directory: "ees/test-ee-2"
            build-with: ansible-navigator
          # - image-registry: "ghcr.io"
          #   image-name: "${{ github.repository }}/test-ee-3"
          #   poetry-version: "1.6.1"
          #   python-version: "3.9.16"
          #   working-directory: "ees/test-ee-3"
          #   build-with: ansible-navigator
          - image-registry: "ghcr.io"
            image-name: "${{ github.repository }}/test-ee-4"
            poetry-version: "1.6.1"
            python-version: "3.9.16"
            working-directory: "ees/test-ee-4"
            build-with: ansible-navigator
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.image.python-version }}

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.image.poetry-version }}

      - name: Poetry install
        working-directory: ${{ matrix.image.working-directory }}
        run: |
          poetry install

      - name: Get yyymmdd
        run: echo "DATE=$(date +%Y%m%d)" >>$GITHUB_ENV

      - name: Build EE with ansible-builder
        if: matrix.image.build-with == 'ansible-builder'
        working-directory: ${{ matrix.image.working-directory }}
        run: |
          echo "::group::Build EE"
          poetry run \
            ansible-builder build \
              --container-runtime docker \
              --tag ${{ matrix.image.image-registry }}/${{ matrix.image.image-name }}:latest \
              --tag ${{ matrix.image.image-registry }}/${{ matrix.image.image-name }}:${{ env.DATE }} \
              --verbosity 3
          echo "::endgroup::"

      - name: Build EE with ansible-navigator
        if: matrix.image.build-with == 'ansible-navigator'
        working-directory: ${{ matrix.image.working-directory }}
        env:
          TERM: xterm256color
        run: |
          echo "::group::Build EE"
          poetry run \
            ansible-navigator builder build \
              --container-runtime docker \
              --container-options 'platform=linux/amd64,linux/arm64/v8' \
              --tag=${{ matrix.image.image-registry }}/${{ matrix.image.image-name }}:latest \
              --tag=${{ matrix.image.image-registry }}/${{ matrix.image.image-name }}:${{ env.DATE }} \
              --verbosity 3
          echo "::endgroup::"

      - name: Login to ${{ matrix.image.registry }} Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ matrix.image.image-registry }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Test EE
        if: matrix.image.build-with == 'ansible-navigator'
        working-directory: ${{ matrix.image.working-directory }}
        env:
          TERM: xterm256color
        run: |
          echo "::group::Test EE"
          poetry run \
            ansible-navigator run test.yml --mode stdout \
              --execution-environment-image ${{ matrix.image.image-registry }}/${{ matrix.image.image-name }}:latest
          echo "::endgroup::"

      - name: Push EE
        working-directory: ${{ matrix.image.working-directory }}
        run: |
          echo "::group::Push EE"
          docker push ${{ matrix.image.image-registry }}/${{ matrix.image.image-name }}:latest
          docker push ${{ matrix.image.image-registry }}/${{ matrix.image.image-name }}:${{ env.DATE }}
          echo "::endgroup::"
